/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecvarldecfoncProgramme extends PProgramme
{
    private POptdecvar _optdecvar_;
    private PListedecfonc _listedecfonc_;

    public ADecvarldecfoncProgramme()
    {
        // Constructor
    }

    public ADecvarldecfoncProgramme(
        @SuppressWarnings("hiding") POptdecvar _optdecvar_,
        @SuppressWarnings("hiding") PListedecfonc _listedecfonc_)
    {
        // Constructor
        setOptdecvar(_optdecvar_);

        setListedecfonc(_listedecfonc_);

    }

    @Override
    public Object clone()
    {
        return new ADecvarldecfoncProgramme(
            cloneNode(this._optdecvar_),
            cloneNode(this._listedecfonc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecvarldecfoncProgramme(this);
    }

    public POptdecvar getOptdecvar()
    {
        return this._optdecvar_;
    }

    public void setOptdecvar(POptdecvar node)
    {
        if(this._optdecvar_ != null)
        {
            this._optdecvar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optdecvar_ = node;
    }

    public PListedecfonc getListedecfonc()
    {
        return this._listedecfonc_;
    }

    public void setListedecfonc(PListedecfonc node)
    {
        if(this._listedecfonc_ != null)
        {
            this._listedecfonc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listedecfonc_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optdecvar_)
            + toString(this._listedecfonc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optdecvar_ == child)
        {
            this._optdecvar_ = null;
            return;
        }

        if(this._listedecfonc_ == child)
        {
            this._listedecfonc_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optdecvar_ == oldChild)
        {
            setOptdecvar((POptdecvar) newChild);
            return;
        }

        if(this._listedecfonc_ == oldChild)
        {
            setListedecfonc((PListedecfonc) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
