/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstrappelInstr extends PInstr
{
    private PInstrappel _instrappel_;

    public AInstrappelInstr()
    {
        // Constructor
    }

    public AInstrappelInstr(
        @SuppressWarnings("hiding") PInstrappel _instrappel_)
    {
        // Constructor
        setInstrappel(_instrappel_);

    }

    @Override
    public Object clone()
    {
        return new AInstrappelInstr(
            cloneNode(this._instrappel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstrappelInstr(this);
    }

    public PInstrappel getInstrappel()
    {
        return this._instrappel_;
    }

    public void setInstrappel(PInstrappel node)
    {
        if(this._instrappel_ != null)
        {
            this._instrappel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instrappel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instrappel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instrappel_ == child)
        {
            this._instrappel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instrappel_ == oldChild)
        {
            setInstrappel((PInstrappel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
