/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ALinstrecListeinst extends PListeinst
{
    private PInstr _instr_;
    private PListeinst _listeinst_;

    public ALinstrecListeinst()
    {
        // Constructor
    }

    public ALinstrecListeinst(
        @SuppressWarnings("hiding") PInstr _instr_,
        @SuppressWarnings("hiding") PListeinst _listeinst_)
    {
        // Constructor
        setInstr(_instr_);

        setListeinst(_listeinst_);

    }

    @Override
    public Object clone()
    {
        return new ALinstrecListeinst(
            cloneNode(this._instr_),
            cloneNode(this._listeinst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALinstrecListeinst(this);
    }

    public PInstr getInstr()
    {
        return this._instr_;
    }

    public void setInstr(PInstr node)
    {
        if(this._instr_ != null)
        {
            this._instr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instr_ = node;
    }

    public PListeinst getListeinst()
    {
        return this._listeinst_;
    }

    public void setListeinst(PListeinst node)
    {
        if(this._listeinst_ != null)
        {
            this._listeinst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listeinst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instr_)
            + toString(this._listeinst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instr_ == child)
        {
            this._instr_ = null;
            return;
        }

        if(this._listeinst_ == child)
        {
            this._listeinst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instr_ == oldChild)
        {
            setInstr((PInstr) newChild);
            return;
        }

        if(this._listeinst_ == oldChild)
        {
            setListeinst((PListeinst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
