/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMoinsExp3 extends PExp3
{
    private PExp3 _exp3_;
    private TMoins _moins_;
    private PExp4 _exp4_;

    public AMoinsExp3()
    {
        // Constructor
    }

    public AMoinsExp3(
        @SuppressWarnings("hiding") PExp3 _exp3_,
        @SuppressWarnings("hiding") TMoins _moins_,
        @SuppressWarnings("hiding") PExp4 _exp4_)
    {
        // Constructor
        setExp3(_exp3_);

        setMoins(_moins_);

        setExp4(_exp4_);

    }

    @Override
    public Object clone()
    {
        return new AMoinsExp3(
            cloneNode(this._exp3_),
            cloneNode(this._moins_),
            cloneNode(this._exp4_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMoinsExp3(this);
    }

    public PExp3 getExp3()
    {
        return this._exp3_;
    }

    public void setExp3(PExp3 node)
    {
        if(this._exp3_ != null)
        {
            this._exp3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp3_ = node;
    }

    public TMoins getMoins()
    {
        return this._moins_;
    }

    public void setMoins(TMoins node)
    {
        if(this._moins_ != null)
        {
            this._moins_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._moins_ = node;
    }

    public PExp4 getExp4()
    {
        return this._exp4_;
    }

    public void setExp4(PExp4 node)
    {
        if(this._exp4_ != null)
        {
            this._exp4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp4_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp3_)
            + toString(this._moins_)
            + toString(this._exp4_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp3_ == child)
        {
            this._exp3_ = null;
            return;
        }

        if(this._moins_ == child)
        {
            this._moins_ = null;
            return;
        }

        if(this._exp4_ == child)
        {
            this._exp4_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp3_ == oldChild)
        {
            setExp3((PExp3) newChild);
            return;
        }

        if(this._moins_ == oldChild)
        {
            setMoins((TMoins) newChild);
            return;
        }

        if(this._exp4_ == oldChild)
        {
            setExp4((PExp4) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
