/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AVartabVar extends PVar
{
    private TIdentif _identif_;
    private TCrochetOuvrant _crochetOuvrant_;
    private PExp _exp_;
    private TCrochetFermant _crochetFermant_;

    public AVartabVar()
    {
        // Constructor
    }

    public AVartabVar(
        @SuppressWarnings("hiding") TIdentif _identif_,
        @SuppressWarnings("hiding") TCrochetOuvrant _crochetOuvrant_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TCrochetFermant _crochetFermant_)
    {
        // Constructor
        setIdentif(_identif_);

        setCrochetOuvrant(_crochetOuvrant_);

        setExp(_exp_);

        setCrochetFermant(_crochetFermant_);

    }

    @Override
    public Object clone()
    {
        return new AVartabVar(
            cloneNode(this._identif_),
            cloneNode(this._crochetOuvrant_),
            cloneNode(this._exp_),
            cloneNode(this._crochetFermant_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVartabVar(this);
    }

    public TIdentif getIdentif()
    {
        return this._identif_;
    }

    public void setIdentif(TIdentif node)
    {
        if(this._identif_ != null)
        {
            this._identif_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identif_ = node;
    }

    public TCrochetOuvrant getCrochetOuvrant()
    {
        return this._crochetOuvrant_;
    }

    public void setCrochetOuvrant(TCrochetOuvrant node)
    {
        if(this._crochetOuvrant_ != null)
        {
            this._crochetOuvrant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crochetOuvrant_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TCrochetFermant getCrochetFermant()
    {
        return this._crochetFermant_;
    }

    public void setCrochetFermant(TCrochetFermant node)
    {
        if(this._crochetFermant_ != null)
        {
            this._crochetFermant_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._crochetFermant_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identif_)
            + toString(this._crochetOuvrant_)
            + toString(this._exp_)
            + toString(this._crochetFermant_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identif_ == child)
        {
            this._identif_ = null;
            return;
        }

        if(this._crochetOuvrant_ == child)
        {
            this._crochetOuvrant_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._crochetFermant_ == child)
        {
            this._crochetFermant_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identif_ == oldChild)
        {
            setIdentif((TIdentif) newChild);
            return;
        }

        if(this._crochetOuvrant_ == oldChild)
        {
            setCrochetOuvrant((TCrochetOuvrant) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._crochetFermant_ == oldChild)
        {
            setCrochetFermant((TCrochetFermant) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
